### ISSUE TITLE
Allmänt

### ISSUE THREAD

**Issue by JuliaSivartsson** [henceee/1dv450-hg222dv#1]
## Övergripande

**Komma igång**

Då jag själv aldrig använt cURL så hade det varit en fördel om det hade funnits en snabb förklaring om hur cURL används, nu löste jag det ganska snabbt men för att underlätta för kanske någon som är mindre tekniskt erfaren så kunde det funnits en liten notis om det i readme-filen för det.

Det verkar inte som att laborationen ligger online någonstans, i och för sig inget krav men hade varit kul att kunna testa allt mot en online server.

**Kod**

Koden känns lite hoppig, det är mycket tabb och mellanslag på raderna (kanske ska vara så, jag är bara inte van vid att läsa kod så)

Väldigt bra och informativa meddelanden åt användaren.

Bra att man kan få resultatet i både json och xml.

**Allmänt**
Det går inte komma åt resurser genom att skriva in api-nyckel i url:en, kanske inte ett måste men det brukar ju vara smidigt.
t.ex. http://test.c9.io/api/shows?key=1234455678900

Jag kommer inte åt resurserna. Jag har registrerat mig, lagt till en app och använder nu den api-nyckeln för att hämta alla shows, men jag får bara "HTTP Token: Access denied." tillbaka.
Har testat både via curl och Postman att anropa api-et, men lyckas inte.

För att kunna testa applikationen i alla fall så ändrade jag lite i koden så att istället för att använda authenticate_or_request_with_http_token, så kollar jag i url-en om det skickas med en api-nyckel: params[:key]. 
T.ex.
http://test.c9.io/api/shows.xml?key=1234455678900

Jag kollar då om den nyckeln finns registrerad i applikationen och på det här sättet fungerar det, jag har ingen koll på hur authenticate_or_request_with_http_token fungerar så tyvärr hittade jag ingen lösning med den metoden.

Jag tror dock inte att tanken är att en api-nyckel ska skickas in som Authorization i headern, men jag kan ha fel. Dock tror jag inte om man kan skicka med två sådana headers och på vissa av anropen ska man ju logga in via JWT eller liknande och där behövs Authorization i headern.

Jag kan se i schema.rb att det finns en tabell för setlists, men jag antar att dessa inte går att komma åt på något sätt. Ser ingen ytterligare info om det i alla all (tänkte så jag inte missat något).

När jag löst ovanstående så testade jag curl-kommandon uppifrån och ner. Resultaten av det lägger jag i olika issues.

_(PS. Måste tillägga att det är sjukt bra band som verkar spela på dina konserter :))_

**Comment by henceee** [comment]
FIXES #1:
Changed authenticate_or_request to a check if params['key'] exists, could reg. a user, create key and use API, so that works now.
